import subprocess
import json
import logging
import shutil
from pathlib import Path
from typing import Dict, Any

from app.core.config import settings

logger = logging.getLogger(__name__)

class GraphifyService:
    """
    Service wrapper for the Graphify CLI to extract ASTs from source code.
    """
    def __init__(self):
        self.cli_path = shutil.which(settings.GRAPHIFY_CLI_PATH) or settings.GRAPHIFY_CLI_PATH

    async def parse_workspace(self, workspace_path: Path) -> Dict[str, Any]:
        """
        Executes graphify on the given directory and returns the AST as a dict.
        """
        if not shutil.which(self.cli_path):
            logger.warning(f"Graphify CLI not found at {self.cli_path}. Using mock AST.")
            return {"mock": "AST generation bypassed"}

        logger.info(f"Running Graphify on {workspace_path}")
        try:
            # According to graphifyy docs, the command is simply `graphify <path>`
            # We add `--code-only` to strictly build the local AST without requiring cloud LLM keys for images/pdfs.
            cmd = [self.cli_path, str(workspace_path), "--code-only"]
            logger.debug(f"Executing: {' '.join(cmd)}")
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )
            
            # Read the generated graph.json file
            graph_file = workspace_path / "graphify-out" / "graph.json"
            if not graph_file.exists():
                logger.error(f"graph.json not found. CLI Output: {result.stdout}")
                raise Exception("graph.json was not generated by Graphify")
                
            with open(graph_file, "r", encoding="utf-8") as f:
                return json.load(f)
                
        except subprocess.CalledProcessError as e:
            logger.error(f"Graphify CLI failed with exit code {e.returncode}. STDERR: {e.stderr}")
            raise Exception(f"AST Extraction failed: {e.stderr}") from e
        except json.JSONDecodeError as e:
            logger.error("Failed to parse Graphify JSON output from file.")
            raise Exception("Invalid AST output format") from e
