"""add_finding_evidence

Revision ID: 02f4d91f8fca
Revises: 0dddf1480df7
Create Date: 2026-09-14 20:18:10.793625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f4d91f8fca'
down_revision: Union[str, Sequence[str], None] = '0dddf1480df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_findings', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('review_findings', sa.Column('why_it_matters', sa.Text(), nullable=True))
    op.add_column('review_findings', sa.Column('confidence', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_findings', 'confidence')
    op.drop_column('review_findings', 'why_it_matters')
    op.drop_column('review_findings', 'evidence')
    # ### end Alembic commands ###
