"""Add review summary stats

Revision ID: 0dddf1480df7
Revises: 9c4e79b3b490
Create Date: 2026-09-14 19:00:34.791834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dddf1480df7'
down_revision: Union[str, Sequence[str], None] = '9c4e79b3b490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_runs', sa.Column('changed_files_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('changed_lines_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('changed_symbols_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('affected_files_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('affected_symbols_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('related_tests_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('review_runs', sa.Column('findings_count', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('high_severity_findings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_runs', 'high_severity_findings_count')
    op.drop_column('review_runs', 'findings_count')
    op.drop_column('review_runs', 'risk_level')
    op.drop_column('review_runs', 'related_tests_count')
    op.drop_column('review_runs', 'affected_symbols_count')
    op.drop_column('review_runs', 'affected_files_count')
    op.drop_column('review_runs', 'changed_symbols_count')
    op.drop_column('review_runs', 'changed_lines_count')
    op.drop_column('review_runs', 'changed_files_count')
    # ### end Alembic commands ###
