"""Add SCM Accounts and Webhooks

Revision ID: 13451c5effaf
Revises: eb6038a812ad
Create Date: 2026-09-14 15:36:12.659788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13451c5effaf'
down_revision: Union[str, Sequence[str], None] = 'eb6038a812ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', postgresql.ENUM('github', 'gitlab', 'bitbucket', name='scmprovider', create_type=False), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scm_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider_hook_id', sa.String(length=255), nullable=False),
    sa.Column('secret_token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('scm_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'scm_accounts', ['scm_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'scm_account_id')
    op.drop_table('scm_webhooks')
    op.drop_table('scm_accounts')
    # ### end Alembic commands ###
