"""Add tokens to ReviewRun

Revision ID: 54473e76b64f
Revises: 13451c5effaf
Create Date: 2026-09-14 15:43:53.872934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54473e76b64f'
down_revision: Union[str, Sequence[str], None] = '13451c5effaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_runs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('review_runs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_runs', 'output_tokens')
    op.drop_column('review_runs', 'input_tokens')
    # ### end Alembic commands ###
