"""add_project_policies

Revision ID: 709e8827961c
Revises: 02f4d91f8fca
Create Date: 2026-09-14 20:21:36.822062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709e8827961c'
down_revision: Union[str, Sequence[str], None] = '02f4d91f8fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ignore_paths', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('review_mode', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('focus_categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'focus_categories')
    op.drop_column('projects', 'review_mode')
    op.drop_column('projects', 'ignore_paths')
    # ### end Alembic commands ###
