"""add_platform_settings

Revision ID: 9c4e79b3b490
Revises: a6495d5dafdb
Create Date: 2026-09-14 17:25:31.211397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4e79b3b490'
down_revision: Union[str, Sequence[str], None] = 'a6495d5dafdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(length=1024), nullable=True),
    sa.Column('google_api_key', sa.String(length=1024), nullable=True),
    sa.Column('default_llm_model', sa.String(length=255), nullable=False),
    sa.Column('severity_threshold', sa.String(length=50), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
