"""add_llm_model_to_webhook

Revision ID: a6495d5dafdb
Revises: 54473e76b64f
Create Date: 2026-09-14 16:44:33.649679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6495d5dafdb'
down_revision: Union[str, Sequence[str], None] = '54473e76b64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scm_webhooks', sa.Column('llm_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scm_webhooks', 'llm_model')
    # ### end Alembic commands ###
