"""Add diff_data to ReviewRun

Revision ID: eb6038a812ad
Revises: 875617fe6539
Create Date: 2026-09-14 12:57:32.360339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6038a812ad'
down_revision: Union[str, Sequence[str], None] = '875617fe6539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_runs', sa.Column('diff_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_runs', 'diff_data')
    # ### end Alembic commands ###
