import logging
import httpx
from typing import List
from app.db.models import ReviewFinding

logger = logging.getLogger(__name__)

class GithubPublisherService:
    """
    Handles interactions with the GitHub REST API to post review comments on Pull Requests.
    """
    def __init__(self, github_token: str):
        self.github_token = github_token
        self.base_url = "https://api.github.com"
        self.headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }

    async def post_pr_summary(self, repo_full_name: str, pr_number: int, findings: List[ReviewFinding]):
        """
        Attempts to post inline review comments. Falls back to a general Markdown table if line numbers are invalid.
        """
        if not findings:
            logger.info("No findings to post.")
            return

        # 1. Attempt to post as an Inline PR Review
        review_url = f"{self.base_url}/repos/{repo_full_name}/pulls/{pr_number}/reviews"
        inline_comments = []
        
        for f in findings:
            if f.line_number and f.file_path:
                severity_str = f.severity.value if hasattr(f.severity, 'value') else str(f.severity)
                emoji = "🔴" if severity_str == "critical" else "🟠" if severity_str == "high" else "🟡"
                
                body = f"**{emoji} {severity_str.upper()}** ({f.category})\n\n{f.description}\n\n"
                if f.suggested_fix:
                    body += f"**Suggested Fix:**\n```python\n{f.suggested_fix}\n```"
                    
                inline_comments.append({
                    "path": f.file_path,
                    "line": f.line_number,
                    "body": body
                })

        async with httpx.AsyncClient() as client:
            if inline_comments:
                logger.info(f"Attempting to post {len(inline_comments)} inline comments to PR #{pr_number}")
                try:
                    review_payload = {
                        "body": "🤖 **AI Review Complete**\n\nI have reviewed the changes and left inline comments.",
                        "event": "COMMENT",
                        "comments": inline_comments
                    }
                    response = await client.post(review_url, headers=self.headers, json=review_payload)
                    response.raise_for_status()
                    logger.info("Successfully posted inline PR review!")
                    return # Exit if successful
                except httpx.HTTPStatusError as e:
                    logger.warning(f"Inline review failed (likely invalid line numbers). Falling back to general comment. {e.response.status_code}")
            
            # 2. Fallback to General Markdown Table Comment
            logger.info("Posting general review summary to PR conversation tab...")
            comment_body = self._format_markdown_summary(findings)
            fallback_url = f"{self.base_url}/repos/{repo_full_name}/issues/{pr_number}/comments"
            
            try:
                response = await client.post(fallback_url, headers=self.headers, json={"body": comment_body})
                response.raise_for_status()
                logger.info("Successfully posted general PR comment fallback.")
            except httpx.HTTPStatusError as e:
                logger.error(f"Failed to post to GitHub: {e.response.status_code} - {e.response.text}")
                raise Exception("GitHub API Error") from e

    def _format_markdown_summary(self, findings: List[ReviewFinding]) -> str:
        """
        Converts the database findings into a beautiful Markdown comment for GitHub.
        """
        md = "## 🤖 AI Review Findings\n\n"
        md += "I have analyzed this Pull Request. Here are the potential issues caught by the AI:\n\n"
        md += "| Severity | Category | File | Line | Description |\n"
        md += "|----------|----------|------|------|-------------|\n"
        
        for f in findings:
            # Handle both Enum objects and raw strings
            severity_str = f.severity.value if hasattr(f.severity, 'value') else str(f.severity)
            
            # Add emojis based on severity
            emoji = "🔴" if severity_str == "critical" else "🟠" if severity_str == "high" else "🟡"
            file_ref = f"`{f.file_path}:{f.line_number}`" if f.line_number else f"`{f.file_path}`"
            
            md += f"| {emoji} {severity_str.upper()} | {f.category} | {file_ref} | {f.line_number} | {f.description} |\n"
            
        md += "\n---\n"
        md += "*Generated by the AI Developer Intelligence Platform.*"
        
        return md
